language: java
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk8
before_install:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - cat target/travis/settings.xml 1>&2
  - echo $GPG_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNER_TRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

install:
  mvn --settings target/travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script: "mvn deploy --settings target/travis/settings.xml"

deploy:
  - provider: releases
    api_key: $github_token
    file:
      - fieldextraction-core/target/fieldextraction-core-$project_version.jar
      - fieldextraction-grok/target/fieldextraction-grok-$project_version.jar
      - fieldextraction-morphlines/target/fieldextraction-morphlines-$project_version.jar
      - fieldextraction-csv/target/fieldextraction-csv-$project_version.jar
      - fieldextraction-jython-regex/target/fieldextraction-jython-regex-$project_version.jar
    skip_cleanup: true
    on:
      tags: true
      repo: secureops/fieldextraction
  - provider: script
    script: "mvn deploy --settings target/travis/settings.xml"
    on:
      tags: true
