language: java
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk8
before_install:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - echo $GPG_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNER_TRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
script: "mvn deploy --settings target/travis/settings.xml"
